server:
  port: 8080
eureka:
  instance:
    hostname: peer3
    #prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    #ip-address: 192.168.0.9 #强制指定IP地址，默认会获取本机的IP地址
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://peer1:8080/eureka/,http://peer2:8080/eureka/,http://peer3:8080/eureka/
