server:
  port: 8025
  servlet:
    context-path: /rabbitmq

# rabbitmq地址
#注意：
#（1）端口号默认为5672，15672是可视化界面的访问端口
#     写错会报 org.springframework.amqp.AmqpTimeoutException: java.util.concurrent.TimeoutException 异常
spring:
  application:
    name: system-rabbitmq-server
    #环境 dev|test|prod
    profiles:
      active: dev
    messages:
      encoding: UTF-8
      basename: i18n/messages_common
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    addresses: 10.0.0.11:5672
    username: admin
    password: 123456
    # 虚拟主机
    virtual-host: /
    # 确认消息发送成功，通过实现ConfirmCallBack接口，消息发送到交换器Exchange后触发回调
    publisher-confirms: true
    # 设置return消息模式，需要配合template.mandatory为true一起使用
    publisher-returns: true
    template:
      mandatory: true
    listener:
      direct:
        auto-startup: false
      simple:
        acknowledge-mode: manual # 消费端核心配置1：消费端收到消息的签收方式（一般都选择 manual手动签收）
        concurrency: 1 # 消费端核心配置2：并行数量，并发大根据cpu等配置进行调整，默认设置为1和max为5
        max-concurrency: 5

############################################################
#
# 线程池 配置
#
############################################################
thread:
  pool:
    thread-pool-name: rabbitmq_client_async_sender # 线程池名称
    core-thread-size: 4 # 核心线程数
    max-thread-size: 8 # 最大线程数
    keep-alive-time: 60 # 线程池中空闲线程等待工作的超时时间
    capacity: 10000 # 线程池容量

############################################################
#
# rabbitmq-consumer 配置
#
############################################################

# 常用queue/exchange/routingKey
queue:
  value: queue-1
  durable: true
exchange:
  name: exchange-1
  durable: true
  type: topic
  ignoreDeclarationExceptions: true
key: routingKey.*

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

# 延迟消息专用queue/exchange/routingKey
delay:
  queue:
    value: delay-queue
    durable: true
  exchange:
    name: delay-exchange
    durable: true
    type: topic
    ignoreDeclarationExceptions: true
  key: delay.*