server:
  port: 8080

spring:
  application:
    name: system-gateway-server
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        #认证服务
        - id: system-auth-server
          uri: lb://system-auth-server
          order: 1
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        #Admin服务
        - id: system-admin-server
          uri: lb://system-admin-server
          order: 2
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=0
        #消息服务
        - id: system-message-server
          uri: lb://system-message-server
          order: 3
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=0
        #定时任务服务
        - id: system-job-server
          uri: lb://system-job-server
          order: 6
          predicates:
            - Path=/job/**
          filters:
            - StripPrefix=0
        #APP流服务
        - id: system-api-server
          uri: lb://system-api-server
          order: 7
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0
        #预购商品服务
        - id: system-shop-server
          uri: lb://system-shop-server
          order: 7
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=0
        #OSS服务
        - id: system-oss-server
          uri: lb://system-oss-server
          order: 8
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=0
        #消息中间件服务
        - id: system-rabbitmq-server
          uri: lb://system-rabbitmq-server
          order: 9
          predicates:
            - Path=/rabbitmq/**
          filters:
            - StripPrefix=0
        #消息中间件服务
        - id: system-api-server
          uri: lb://system-api-server
          order: 10
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      management:
        context-path: /actuator
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #缺省为1000

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000

renren:
  urls:
  #请求图形验证码
    - /auth/captcha
  #请求数字验证码
    - /api/auth/captcha
  #PC登录
    - /auth/login
  #手机APP登录
    - /api/auth/login
  #消息中间件（临时）
    - /rabbitmq/*